# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protos/greeting.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import AsyncGenerator, List

import betterproto
import grpclib


@dataclass
class EchoRequest(betterproto.Message):
    value: str = betterproto.string_field(1)
    # Number of extra times to echo
    extra_times: int = betterproto.uint32_field(2)


@dataclass
class EchoResponse(betterproto.Message):
    values: List[str] = betterproto.string_field(1)


@dataclass
class EchoStreamResponse(betterproto.Message):
    value: str = betterproto.string_field(1)


class EchoStub(betterproto.ServiceStub):
    async def echo(self, *, value: str = "", extra_times: int = 0) -> EchoResponse:
        request = EchoRequest()
        request.value = value
        request.extra_times = extra_times

        return await self._unary_unary(
            "/echo.Echo/Echo",
            request,
            EchoResponse,
        )

    async def echo_stream(
        self, *, value: str = "", extra_times: int = 0
    ) -> AsyncGenerator[EchoStreamResponse, None]:
        request = EchoRequest()
        request.value = value
        request.extra_times = extra_times

        async for response in self._unary_stream(
            "/echo.Echo/EchoStream",
            request,
            EchoStreamResponse,
        ):
            yield response
