# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protos/square.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class Number(betterproto.Message):
    value: int = betterproto.int32_field(1)


@dataclass
class Result(betterproto.Message):
    value: int = betterproto.int32_field(1)


class SquareServiceStub(betterproto.ServiceStub):
    async def get_square(self, *, value: int = 0) -> Result:
        request = Number()
        request.value = value

        return await self._unary_unary(
            "/square.SquareService/GetSquare",
            request,
            Result,
        )
